version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .config/web/env.dev
    command: python manage.py runserver 0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"