version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --certfile=/etc/certs/localhost.crt --keyfile=/etc/certs/localhost.key business_doggies.wsgi:application --bind 0.0.0.0:443"
    environment:
      - SECRET_KET='n35_u84qs^#qo%ehzcm3bc!dq0m^(%6fe$(ld1c%uqr90ku&*^"'
    volumes:
      - .:/app
      - ./config/nginx/certs/:/etc/certs
    expose:
      - "443"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - .config/nginx/:/etc/nginx/conf.d
    depends_on:
      - web
