version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .config/db/.env.dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .config/web/.env.dev
    command: python manage.py runserver 0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db