version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn business_doggies.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .config/web/env.prod
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:
      - .config/db/env.prod
  nginx:
    build: .nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
    
volumes:
  postgres_data:
  static_volume:
  media_volume: